### ISSUE TITLE
приближение f(x) финитной

### ISSUE THREAD

**Issue by p0l0satik** [MrG1raffe/PT-MS#9]
как и на каком основании мы делаем описанное в пункте

**Comment by igudav** [comment]
Для этого не нужно основание. Это определение, а не доказательство, в определении мы можем делать, что захотим, лишь бы оно было корректным (т.е. описываемые объекты существовали бы). А тут мы просто захотели вот именно таким образом приближать функцию, чтобы определить интеграл Лебега.
